
language: java
sudo: false # faster builds

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: s3
  access_key_id: 
  secret_access_key: 
  bucket: testsiteawf
  local-dir: /git_tst/index.html
  region: us-west-2
