
language: java
sudo: false # faster builds

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: s3
  access_key_id: AKIAIGLRLQS6G23SCN2Q
  secret_access_key: GnEPUIa164mjFzoMwuow+gH55XHBnO3uNmuVHF69
  bucket: awf-example.com
  local-dir: /git_tst/index.html
